name: Generate Environment Variables for Frontend

on:
  push:
    branches:
      - main

jobs:
  generate_env_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Generate Environment Variables File
        run: |
          echo "REACT_APP_API_URL=${{ secrets.API_URL }}" > .env
        env:
          API_URL: ${{ secrets.API_URL }}

      - name: Commit Environment Variables File
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Generate environment variables for frontend"
          git push
